apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/Wafi-inc/devops-interview'
    path: 'k8s'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
